// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rksmsdzgwkmbhakcgalb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrc21zZHpnd2ttYmhha2NnYWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4OTAxNjEsImV4cCI6MjA3NTQ2NjE2MX0.BfqLEFgYr3t0sDVbUtkWQbg5XfSg3ITCYBvd4DeFhR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});